## Schema Getter

### Packages and Environment setting

In [1]:
## Packages
import numpy as np
import pandas as pd
import time
import datetime
pd.set_option('display.max_columns', 300)
pd.set_option('display.max_rows', 1000)
pd.options.display.max_colwidth = 1000
import os
import math

## env
PATH_RAW = '/Users/jerry/Desktop/example/'        ## input path
PATH_OUT = '/Users/jerry/Desktop/dataBase/DataProcessed/' ## output path
encoding = 'utf-8'

### Header columns information

In [5]:
os.chdir(PATH_RAW)
lst = os.listdir()
lst = [lst for lst in lst if '.csv' in lst]

data_store = pd.DataFrame(columns = ['index', 'col'])

for x in list(range(len(lst))):
    temp = pd.read_csv(str(lst[x]), nrows = 0, encoding = encoding)
    temp = temp.T.reset_index().reset_index()
    temp.columns = ['index', 'col']
    temp['index'] = str(lst[x])
    data_store = pd.concat([data_store, temp])
    
data_store['index'] = data_store['index'].str.replace('.csv', '')

data_store = data_store.sort_values(by = 'index')
data_store.columns = ['csv_name', 'col_name']

os.chdir(PATH_OUT)
data_store.to_csv('header_all.csv')
display(data_store)

           csv_name      col_name
0  Family_condition        Family
1  Family_condition       Brother
2  Family_condition        Sister
3  Family_condition   CheckInDate
4  Family_condition  CheckOutDate
5  Family_condition        Status
6  Family_condition          Note
4      Measurements        Height
3      Measurements        Weight
2      Measurements      Activity
1      Measurements    Bloodsugar
0      Measurements   Temperature
6      Measurements       Address
5      Measurements          NAME
6              Test    Unnamed: 6
4              Test        Status
2              Test          Type
1              Test          Date
0              Test         Score
5              Test       Contact
3              Test    Suggestion

### With dtypes information

In [2]:
os.chdir(PATH_RAW)
lst = os.listdir()
lst = [lst for lst in lst if '.csv' in lst]
    
data_store = pd.DataFrame()

for x in list(range(len(lst))):
    temp = pd.read_csv(str(lst[x]), encoding = encoding, error_bad_lines=False, nrows = 30)
    temp = pd.DataFrame(temp.dtypes, columns = ['dtypes']).reset_index()
    temp['csv_name'] = str(lst[x])

    data_store = pd.concat([data_store, temp])

data_store['csv_name'] = data_store['csv_name'].str.replace('.csv', '')
data_store = data_store.sort_values(by = 'csv_name')
data_store = data_store[['csv_name', 'index', 'dtypes']]
data_store = data_store.rename(columns = {'index': 'col_name'})

os.chdir(PATH_OUT)
data_store.to_csv('header_all_dtypes.csv')   

display(data_store)

           csv_name      col_name   dtypes
0  Family_condition        Family  float64
1  Family_condition       Brother  float64
2  Family_condition        Sister  float64
3  Family_condition   CheckInDate   object
4  Family_condition  CheckOutDate   object
5  Family_condition        Status   object
6  Family_condition          Note   object
4      Measurements        Height  float64
3      Measurements        Weight  float64
2      Measurements      Activity   object
1      Measurements    Bloodsugar  float64
0      Measurements   Temperature  float64
6      Measurements       Address   object
5      Measurements          NAME   object
6              Test    Unnamed: 6  float64
4              Test        Status   object
2              Test          Type  float64
1              Test          Date   object
0              Test         Score  float64
5              Test       Contact   object
3              Test    Suggestion   object